Repository gardener/oidc-apps-controller, pull requests merged in 2025-02, with the labels that each got.

#123 Remove VPA for sidecar containers
  pkg/webhook/test/vpa-mutating-webhook_test.go
  pkg/webhook/vpa-webhook.go
Labels: reviewed/lgtm, needs/ok-to-test, size/s

#128 Update kube-rbac-proxy-watcher to 0.1.8
  imagevector/images.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#129 Publish helm chart to OCI registry
  .ci/pipeline_definitions
Labels: reviewed/lgtm, needs/ok-to-test, needs/review, size/xs

#130 chore(deps): bump up kube-rbac-proxy-watcher to 0.1.9
  imagevector/images.yaml
Labels: needs/ok-to-test, needs/review, size/xs
