Repository gardener/oidc-apps-controller, pull requests merged in 2025-07, with the labels that each got.

#206 Update tool dependencies
  go.mod
  go.sum
Labels: needs/ok-to-test, needs/review, size/xs

#211 Remove memory limits
  example/provider-local/oidc-apps-controller-registration.yaml
Labels: needs/review, size/xs

#217 Update oauth2-proxy to v7.10.0
  imagevector/images.yaml
Labels: needs/review, size/xs

#220 export testresults as inlined ocm-resource
  .github/workflows/build.yaml
Labels: needs/review, size/s
