Repository gardener/oidc-apps-controller, pull requests merged in 2025-04, with the labels that each got.

#150 Update ci verify image
  .ci/pipeline_definitions
Labels: needs/ok-to-test, needs/review, size/xs

#151 Update go to 1.24.2
  Dockerfile
  go.mod
Labels: needs/ok-to-test, needs/review, size/xs

#152 Update sidecars containers
  imagevector/images.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#154 Update build tools dependencies
  go.mod
  go.sum
Labels: needs/ok-to-test, needs/review, size/m

#157 Switch Slack references to Gardener workspace
  README.md
Labels: area/open-source, kind/enhancement, reviewed/lgtm, size/xs

#160 Simple lint configuration
  .golangci.yaml
Labels: needs/ok-to-test

#161 Update tool dependencies
  go.mod
  go.sum
Labels: needs/ok-to-test, needs/review, size/s

#163 Remove RBAC wildcard references
  charts/oidc-apps-controller/templates/clusterrole.yaml
  example/controller-registration.yaml
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs

#164 Update dependabot configuration
  .github/dependabot.yml
Labels: needs/ok-to-test, needs/review, size/xs
